"syndna_indiv_ng_ul":
    # concentrations taken from table in Fig. 1A of
    # https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9765022/
    "pool1":
        "p126": 1
        "p136": 0.1
        "p146": 0.01
        "p156": 0.001
        "p166": 0.0001
        "p226": 0.0001
        "p236": 0.001
        "p246": 0.01
        "p256": 0.1
        "p266": 1
    "pool1000":
        "synDNA_16SrRNA_seq_1_gc=0.26": 1
        "synDNA_16SrRNA_seq_1_gc=0.36": 0.1
        "synDNA_16SrRNA_seq_1_gc=0.46": 0.01
        "synDNA_16SrRNA_seq_1_gc=0.56": 0.001
        "synDNA_16SrRNA_seq_1_gc=0.66": 0.0001
        "synDNA_16SrRNA_seq_2_gc=0.26": 0.0001
        "synDNA_16SrRNA_seq_2_gc=0.36": 0.001
        "synDNA_16SrRNA_seq_2_gc=0.46": 0.01
        "synDNA_16SrRNA_seq_2_gc=0.56": 0.01
        "synDNA_16SrRNA_seq_2_gc=0.66": 1
